### PR TITLE
Transfer FastBlurHash JS from DLR

### PR DESCRIPTION
**Pull request by sneridagh**

### CODE REVIEW

**Review by reekitconcept — CHANGES_REQUESTED** [review]
There is also a script that does the compilation. That should be added too.

```.PHONY: build-fast-blurhash
build-fast-blurhash: ## Build the code to be embedded into the html
	NODE_ENV=production yarn webpack --config ./src/addons/kitconcept.volto-blocks/src/components/ImageLoader/webpack.fast-blurhash.config.js
```

**Comment by reekitconcept** [comment]
> There is also a script that does the compilation. That should be added too.
> 
> ```
> build-fast-blurhash: ## Build the code to be embedded into the html
> 	NODE_ENV=production yarn webpack --config ./src/addons/kitconcept.volto-blocks/src/components/ImageLoader/webpack.fast-blurhash.config.js
> ```

Ah ok, now I see it's in the other PR. In this case I approve. Point is it has to be run each time the code changes, because the fast blurhash code is not handled  by the central webpack config.

**Review by reekitconcept — APPROVED** [review]

**Comment by davisagli** [comment]
There is also some backend code related to the blurhash, to calculate it when the image scale data is generated.

**Comment by sneridagh** [comment]
@davisagli yes, we need to decide in which package we put that code.

@reekitconcept I added it before, in another PR.

So, merging for now.

**Pull request merged**
